resources:
  - name: spring-petclinic-git
    type: git
    webhook_token: {{webhook-token}}
    source:
      uri: https://github.com/tybritten-org/spring-petclinic
  - name: spring-petclinic-git-release
    type: github-release
    source:
      owner: tybritten-org
      repository: spring-petclinic
      access_token: {{gh-access-token}}
  - name: docker-image
    type: docker-image
    source:
      username: {{harbor-username}}
      password: {{harbor-password}}
      repository: {{repository}}
    
jobs:
- name: build-dev
  plan:
  - get: spring-petclinic-git
    trigger: true
  - task: build-and-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
          tag: 3.6-jdk-8-alpine
      inputs:
      - name: spring-petclinic-git
        path: source
      outputs:
      - name: target
        path: target
      run:
        path: bash
        args:
          - "-c"
          - |
            mvn -Dmaven.repo.local=$(pwd)/cache -f $(pwd)/source/pom.xml clean install
            find source/target -name *.jar -exec mv "{}" target/spring-petclinic.jar \;
            cp  source/Dockerfile target/Dockerfile
      caches:
        - path: cache/ 
  - put: docker-image
    params:
      
      build: target
      tag_as_latest: true

- name: build-prod
  plan:
  - get: spring-petclinic-git-release
    trigger: true
    params:
      include_source_tarball: true
  - task: build-and-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
          tag: 3.6-jdk-8-alpine
      inputs:
      - name: spring-petclinic-git-release
        path: release
      outputs:
      - name: target
        path: target
      run:
        path: bash
        args:
          - "-c"
          - |
            mkdir source
            tar -xzvf release/source.tar.gz --strip-components=1 -C source/
            mvn -Dmaven.repo.local=$(pwd)/cache -f $(pwd)/source/pom.xml clean install
            find source/target -name *.jar -exec mv "{}" target/spring-petclinic.jar \;
            cp  source/Dockerfile target/Dockerfile
      caches:
        - path: cache/ 
  - put: docker-image
    params:
      build: target
      tag_file: spring-petclinic-git-release/tag
      tag_as_latest: false
  
